version: 2.1
jobs:
  build:
    docker:
      - image: cimg/2.6-browsers
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
        environment:
          RAILS_ENV: test
          PG_TEST_HOST: localhost
          PG_TEST_PORT: 5432
          PG_TEST_DATABASE: glass_test
          PG_TEST_USERNAME: ubuntu
          CIRCLECI_ENV: circleci
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
      - image: circleci/postgres:9.6
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: ubuntu
          POSTGRES_DB: glass_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-gemfile-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v2-gemfile-{{ arch }}-{{ .Branch }}
            - v2-gemfile-{{ arch }}-
      - run:
          name: Listing gems
          command: gem list
      - run:
          name: install dependencies
          command: bundle install
      - save_cache:
          key: v2-gemfile-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Database setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load
      # run tests!
      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            --format progress \
                            $TEST_FILES
      # Security analysis
      # - run: bundle exec brakeman
