module Report
  module Footer
    module GeneratedInfo

      FOOTER_HEIGHT = 30

      def draw_footer

        @pdf.bounding_box([@pdf.bounds.left, @pdf.bounds.bottom + FOOTER_HEIGHT], width: @pdf.bounds.width) do

          @absolute_top_footer = @pdf.bounds.absolute_top

          @pdf.pad(10) do
            @pdf.text "Generated by: <strong>#{@user.username}</strong> on #{@generated_at}", align: :center, font_size: 10, inline_format: true
          end

          @pdf.stroke_bounds

        end

      end
    end
  end
end
